/**
 * Full-report generation for `beacon report`.
 *
 * Turns a {@link BeaconAnalysis} into a complete, shareable document in one of
 * three formats: Markdown (default), a self-contained HTML page, or raw JSON.
 * Every renderer is a pure function of the analysis so output is deterministic
 * and testable without a TTY.
 */

import type {
  BeaconAnalysis,
  ContributorStat,
  PillarScore,
  ReleaseInfo,
  ScorePillar,
} from '@beacon/shared';

export type ReportFormat = 'markdown' | 'html' | 'json';

const PILLAR_LABELS: Record<ScorePillar, string> = {
  activity: 'Activity',
  community: 'Community',
  maintenance: 'Maintenance',
  documentation: 'Documentation',
  security: 'Security',
};

function starRating(total: number): string {
  const filled = Math.round(total / 20);
  return `${'★'.repeat(filled)}${'☆'.repeat(Math.max(0, 5 - filled))}`;
}

function topContributors(contributors: ContributorStat[], limit = 10): ContributorStat[] {
  return [...contributors].sort((a, b) => b.contributions - a.contributions).slice(0, limit);
}

function recentReleases(releases: ReleaseInfo[], limit = 5): ReleaseInfo[] {
  return releases.slice(0, limit);
}

function commitsInLast(pillars: PillarScore[]): string {
  const activity = pillars.find((p) => p.pillar === 'activity');
  return activity?.reasons[0] ?? 'Activity data unavailable.';
}

function formatDate(iso: string | null): string {
  if (!iso) {
    return 'unknown';
  }
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? 'unknown' : date.toISOString().slice(0, 10);
}

/** Render a full report as GitHub-flavored Markdown. */
export function renderReportMarkdown(analysis: BeaconAnalysis): string {
  const { snapshot, score, summary } = analysis;
  const { metadata } = snapshot;
  const lines: string[] = [];

  lines.push(`# Beacon Report — ${metadata.fullName}`);
  lines.push('');
  if (metadata.description) {
    lines.push(`> ${metadata.description}`);
    lines.push('');
  }
  if (metadata.htmlUrl) {
    lines.push(metadata.htmlUrl);
    lines.push('');
  }

  lines.push('## Beacon Score');
  lines.push('');
  lines.push(`**${score.total}/100** ${starRating(score.total)} — ${score.grade}`);
  lines.push('');

  lines.push('## Pillars');
  lines.push('');
  lines.push('| Pillar | Score | Signal |');
  lines.push('| --- | --- | --- |');
  for (const pillar of score.pillars) {
    const reason = pillar.reasons[0] ?? '';
    lines.push(`| ${PILLAR_LABELS[pillar.pillar]} | ${pillar.score}/100 | ${reason} |`);
  }
  lines.push('');

  if (score.strengths.length > 0) {
    lines.push('## Strengths');
    lines.push('');
    for (const strength of score.strengths) {
      lines.push(`- ${strength}`);
    }
    lines.push('');
  }
  if (score.warnings.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const warning of score.warnings) {
      lines.push(`- ${warning}`);
    }
    lines.push('');
  }

  lines.push('## Activity');
  lines.push('');
  lines.push(`- ${commitsInLast(score.pillars)}`);
  lines.push(`- Last push: ${formatDate(metadata.pushedAt)}`);
  lines.push(`- Created: ${formatDate(metadata.createdAt)}`);
  lines.push(`- Primary language: ${metadata.primaryLanguage ?? 'n/a'}`);
  lines.push('');

  const contributors = topContributors(snapshot.contributors);
  if (contributors.length > 0) {
    lines.push('## Contributors');
    lines.push('');
    lines.push('| Contributor | Contributions |');
    lines.push('| --- | --- |');
    for (const c of contributors) {
      lines.push(`| ${c.login} | ${c.contributions} |`);
    }
    lines.push('');
  }

  const releases = recentReleases(snapshot.releases);
  if (releases.length > 0) {
    lines.push('## Releases');
    lines.push('');
    lines.push('| Tag | Published |');
    lines.push('| --- | --- |');
    for (const r of releases) {
      lines.push(`| ${r.tagName} | ${formatDate(r.publishedAt)} |`);
    }
    lines.push('');
  }

  lines.push('## Beacon Summary');
  lines.push('');
  lines.push(`_via ${summary.model ? `${summary.provider}/${summary.model}` : summary.provider}_`);
  lines.push('');
  lines.push(summary.text);
  if (summary.highlights.length > 0) {
    lines.push('');
    for (const highlight of summary.highlights) {
      lines.push(`- ${highlight}`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`Generated by Beacon on ${formatDate(new Date().toISOString())}.`);
  lines.push('');

  return lines.join('\n');
}

/** Escape a string for safe inclusion in HTML text/attributes. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function gradeColor(total: number): string {
  if (total >= 75) return '#2ea043';
  if (total >= 50) return '#d29922';
  return '#f85149';
}

/** Render a full report as a self-contained, styled HTML page. */
export function renderReportHtml(analysis: BeaconAnalysis): string {
  const { snapshot, score, summary } = analysis;
  const { metadata } = snapshot;

  const pillarRows = score.pillars
    .map((pillar) => {
      const label = PILLAR_LABELS[pillar.pillar];
      const width = Math.max(0, Math.min(100, pillar.score));
      return `<tr>
        <th scope="row">${escapeHtml(label)}</th>
        <td class="bar"><span style="width:${width}%;background:${gradeColor(pillar.score)}"></span></td>
        <td class="num">${pillar.score}</td>
        <td class="reason">${escapeHtml(pillar.reasons[0] ?? '')}</td>
      </tr>`;
    })
    .join('\n');

  const contributorRows = topContributors(snapshot.contributors)
    .map((c) => `<tr><td>${escapeHtml(c.login)}</td><td class="num">${c.contributions}</td></tr>`)
    .join('\n');

  const releaseRows = recentReleases(snapshot.releases)
    .map(
      (r) =>
        `<tr><td>${escapeHtml(r.tagName)}</td><td>${escapeHtml(formatDate(r.publishedAt))}</td></tr>`,
    )
    .join('\n');

  const highlights = summary.highlights.map((h) => `<li>${escapeHtml(h)}</li>`).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Beacon Report — ${escapeHtml(metadata.fullName)}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 2.5rem 1.25rem;
    font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: #0d1117; color: #e6edf3;
  }
  main { max-width: 780px; margin: 0 auto; }
  h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
  h2 { font-size: 1.15rem; margin: 2rem 0 .75rem; border-bottom: 1px solid #30363d; padding-bottom: .35rem; }
  a { color: #58a6ff; }
  .desc { color: #8b949e; margin: 0 0 1.5rem; }
  .score { display: flex; align-items: baseline; gap: .75rem; }
  .score .total { font-size: 2.75rem; font-weight: 700; color: ${gradeColor(score.total)}; }
  .score .grade { font-size: 1.1rem; color: #8b949e; }
  .stars { color: #d29922; letter-spacing: 2px; font-size: 1.35rem; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: .45rem .5rem; border-bottom: 1px solid #21262d; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  td.reason { color: #8b949e; font-size: .9rem; }
  td.bar { width: 40%; }
  td.bar span { display: block; height: .55rem; border-radius: 999px; }
  ul { padding-left: 1.2rem; }
  .summary { background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 1rem 1.25rem; }
  .via { color: #8b949e; font-size: .85rem; margin: 0 0 .5rem; }
  footer { margin-top: 2.5rem; color: #8b949e; font-size: .8rem; }
</style>
</head>
<body>
<main>
  <h1>${escapeHtml(metadata.fullName)}</h1>
  ${metadata.description ? `<p class="desc">${escapeHtml(metadata.description)}</p>` : ''}
  ${metadata.htmlUrl ? `<p><a href="${escapeHtml(metadata.htmlUrl)}">${escapeHtml(metadata.htmlUrl)}</a></p>` : ''}

  <h2>Beacon Score</h2>
  <div class="score">
    <span class="total">${score.total}</span>
    <span class="grade">/ 100 — ${escapeHtml(score.grade)}</span>
    <span class="stars">${starRating(score.total)}</span>
  </div>

  <h2>Pillars</h2>
  <table><tbody>
  ${pillarRows}
  </tbody></table>

  <h2>Activity</h2>
  <table><tbody>
    <tr><th scope="row">Signal</th><td>${escapeHtml(commitsInLast(score.pillars))}</td></tr>
    <tr><th scope="row">Last push</th><td>${escapeHtml(formatDate(metadata.pushedAt))}</td></tr>
    <tr><th scope="row">Created</th><td>${escapeHtml(formatDate(metadata.createdAt))}</td></tr>
    <tr><th scope="row">Primary language</th><td>${escapeHtml(metadata.primaryLanguage ?? 'n/a')}</td></tr>
  </tbody></table>

  ${
    contributorRows
      ? `<h2>Contributors</h2><table><thead><tr><th>Contributor</th><th class="num">Contributions</th></tr></thead><tbody>${contributorRows}</tbody></table>`
      : ''
  }

  ${
    releaseRows
      ? `<h2>Releases</h2><table><thead><tr><th>Tag</th><th>Published</th></tr></thead><tbody>${releaseRows}</tbody></table>`
      : ''
  }

  <h2>Beacon Summary</h2>
  <div class="summary">
    <p class="via">via ${escapeHtml(summary.model ? `${summary.provider}/${summary.model}` : summary.provider)}</p>
    <p>${escapeHtml(summary.text)}</p>
    ${highlights ? `<ul>${highlights}</ul>` : ''}
  </div>

  <footer>Generated by Beacon on ${escapeHtml(formatDate(new Date().toISOString()))}.</footer>
</main>
</body>
</html>
`;
}

/** Render the full analysis as pretty-printed JSON. */
export function renderReportJson(analysis: BeaconAnalysis): string {
  return JSON.stringify(analysis, null, 2);
}

/** Dispatch to the renderer for `format`. */
export function renderReport(analysis: BeaconAnalysis, format: ReportFormat): string {
  switch (format) {
    case 'json':
      return renderReportJson(analysis);
    case 'html':
      return renderReportHtml(analysis);
    case 'markdown':
      return renderReportMarkdown(analysis);
    default:
      return renderReportMarkdown(analysis);
  }
}
